fix run-st

diff --git a/run-st b/run-st
--- a/run-st
+++ b/run-st
@@ -39,8 +39,10 @@ LOG_FILE="${TESTCASE_ID}.log"
  
 # == change jmeter parameters(ex:HEAP) ==
 jmeter_path=/jmeter/apache-jmeter-3.3/bin
-kubectl exec -it ${MASTER_POD} -- sed "s@HEAP=\"-Xms512m -Xmx512m\"@HEAP=\"-Xms512m -Xmx${MAX_JVM_MEM}\"@g" ${jmeter_path}/jmeter > ./tmp
-kubectl cp ./tmp ${MASTER_POD}:${jmeter_path}/jmeter 
+eval "kubectl cp ${MASTER_POD}:${jmeter_path}/jmeter jmeter"
+sed "s@HEAP=\"-Xms512m -Xmx512m\"@HEAP=\"-Xms512m -Xmx${MAX_JVM_MEM}\"@g" ./jmeter > ./tmp && mv ./tmp ./jmeter
+chmod +x ./jmeter
+eval "kubectl cp ./jmeter ${MASTER_POD}:${jmeter_path}/jmeter"
 # ======================
 
 
@@ -53,13 +55,16 @@ mkdir -p results
 NAME=$(basename ${JMX_FILE})
 NAME="${NAME%.*}"
 
-kubectl exec ${MASTER_POD} -- mkdir -p $WDIR/scripts
-kubectl cp ${JMX_FILE} ${MASTER_POD}:$WDIR/scripts
-kubectl exec -it ${MASTER_POD} -- mkdir -p ${NAME}
-kubectl exec -it ${MASTER_POD} -- jmeter -n -t ./scripts/${NAME}.jmx -e -l ${NAME}/${OUTPUT_FILE} -j ${NAME}/${LOG_FILE} -R ${SLAVE_IP}
-kubectl cp ${MASTER_POD}:$WDIR/$NAME/${OUTPUT_FILE} results/${OUTPUT_FILE}
-kubectl exec -it ${MASTER_POD} -- rm -rf ${NAME}
-kubectl exec -it ${MASTER_POD} -- rm -rf /jmeter/apache-jmeter-3.3/bin/report-output
+eval "kubectl exec ${MASTER_POD} -- mkdir -p $WDIR/scripts"
+eval "kubectl cp ${JMX_FILE} ${MASTER_POD}:$WDIR/scripts"
+eval "kubectl exec -it ${MASTER_POD} -- mkdir -p ${NAME}"
+eval "kubectl exec -it ${MASTER_POD} -- jmeter -n -t ./scripts/${NAME}.jmx -e -l ${NAME}/${OUTPUT_FILE} -j ${NAME}/${LOG_FILE} -R ${SLAVE_IP}"
+if [ $? -eq 0 ]; then
+  eval "kubectl cp ${MASTER_POD}:$WDIR/$NAME/${OUTPUT_FILE} results/${OUTPUT_FILE}"
+  eval "kubectl exec -it ${MASTER_POD} -- rm -rf ${NAME}"
+  eval "kubectl exec -it ${MASTER_POD} -- rm -rf /jmeter/apache-jmeter-3.3/bin/report-output"
 
-echo "***** Finish successfully !!! *****"
-
+  echo "***** Finish successfully !!! *****"
+else 
+  echo "***** Fail to test *****"
+fi
